### ISSUE TITLE
[Wasm] Wrong mouse pointer icon shows up when hovering on any options under the menu list

### ISSUE THREAD

**Issue by jeromelaban** [nventive/calculator#104]
# Repro Steps:
Click on Hamburger menu option 
Hover over any option and observe the mouse pointer icon.

# Actual Result:
It shows I-beam pointer instead of Link pointer (Hand icon) or simple pointer icon.

# Expected Result:
There is always Link pointer (Hand icon) or simple pointer icon for any links or any options.

**Comment by rye761** [comment]
I am unable to reproduce this in Chrome or Firefox. It shows a standard pointer icon.

**Comment by marknoble** [comment]
I was unable to reproduce this in Microsoft Edge Version 88.0.705.50 (Official build) (64-bit).

I navigated to https://calculator.platform.uno/

I saw an index finger pointer cursor on the hamburger menu (the Windows 10 calculator app [Version 10.2012.21.0] had a up and left-pointing arrow).

All items in this menu featured an up and left-pointing arrow (matching the Windows 10 app).

At no point did I see an I-beam pointer.

@jeromelaban What specific browser and version were you using when you encountered this error?

<blockquote><div><strong><a href="https://calculator.platform.uno/">Uno Calculator</a></strong></div><div>The Uno Calculator, a WebAssembly application developed with the Uno Platform, also available for iOS and Android.</div></blockquote>

**Comment by jeromelaban** [comment]
I cannot reproduce either. It's likely that this issue was fixed a while back on related work. Thanks for the troubleshooting!
