### ISSUE TITLE
[Wasm] Programmer calculator keys are not highlighted when it is selected

### ISSUE THREAD

**Issue by jeromelaban** [nventive/calculator#106]
# Repro Steps:
- Click on Hamburger menu option and select Programmer mode.
- Click on the bit toggling key and observe the key.
- Then again click on the full keypad.
- Repeat step 3 & 4 and observe both the keys' states. 

# Actual Result:
Both keys (Bit toggling key and Full keypad key) are not getting highlighted when it is selected.

# Expected Result:
Key is getting highlighted with a different color when it is selected.

**Comment by Hpancha** [comment]
This issue is no longer occurred on the latest WASM build.
**Version:** 0.1.0-uno.1+512
