### ISSUE TITLE
[WASM] User can't scroll down the menu after resizing the browser

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#109]
### **Steps To Reproduce:**

1. Visit [WASM Calculator](http://calculator-wasm-staging.azurewebsites.net/).
2. Resize the browser and adjust in low resolution as much as possible.
3. Open the Menu option and try to scroll down the list.

### **Actual behavior:**

- User is not able to scroll the menu option.

### **Expected behavior:**

- User is able to scroll the menu options using mouse scroll.

### **Screenshot:**

![Inactive_ScrollBar](https://user-images.githubusercontent.com/51453677/59053697-04c88980-8860-11e9-8f9b-b90d3d590f93.png)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+465
 - **Environment:** Firefox, Chrome and Microsoft Edge 

### **Notes:**

- Crosschecked with windows calculator.
- See the attached image to get better idea.

**Comment by jeromelaban** [comment]
This behavior is expected, for the size of the app. The original app is not meant to be this small, we may adjust it in the future.
