### ISSUE TITLE
[WASM] Converted numbers are missing in all the converters

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#110]
### **Steps To Reproduce:**

1. Visit [WASM Calculator](http://calculator-wasm-staging.azurewebsites.net/).
2. Open the Menu and select the **Weight and Mass** converter.
3. Enter any numbers and look at the converted numbers under the "About equal to".

### **Actual behavior:**

- Some of the numbers are missing. Only units show up.

### **Expected behavior:**

- Relative converted numbers always show up with their respective units.

### **Screenshot:**

![Converted_Numbers](https://user-images.githubusercontent.com/51453677/59064357-1158dc00-8878-11e9-91b8-8eb5e31caf92.png)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+465
 - **Environment:** Firefox, Chrome and Microsoft Edge 

### **Notes:**
- IT's mostly happened with all the converters
- What I observe is that it's mostly happened with the lower numbers.
- Crosschecked with windows calculator.
- See the attached image to get better idea.

**Comment by jeromelaban** [comment]
To validate after https://github.com/nventive/Uno/pull/1034
