### ISSUE TITLE
[WASM] Temperature value is rounded up in kelvin

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#111]
### **Steps To Reproduce:**

1. Visit [WASM Calculator](http://calculator-wasm-staging.azurewebsites.net/).
2. Open the Menu and select the **Temperature** converter.
3. Set the value 0 Celsius and observe the value in kelvin under"About equal to".

### **Actual behavior:**

- The temperature in kelvin is rounded up (0 C = 273.2K)

### **Expected behavior:**

- Temperature is rounded down to 273.1K.
- The original value is 273.15K but in windows calculator, the value is rounded down to 273.1K.

### **Screenshot:**

![Rounded_Temp_Value](https://user-images.githubusercontent.com/51453677/59065900-cd67d600-887b-11e9-92f4-618f22446c25.png)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+465
 - **Environment:** Firefox, Chrome and Microsoft Edge 

### **Notes:**
- Crosschecked with windows calculator and the kelvin value is rounded down to 273.1K.
- See the attached image to get better idea.

**Comment by jeromelaban** [comment]
The rounding used by C#/.NET after translation differs from the one used in C++, this is an expected result.
