### ISSUE TITLE
[WASM] Memory cache does not clear by deleting the memory

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#118]
### **Steps To Reproduce:**

1. Visit [WASM Calculator](http://calculator-wasm-staging.azurewebsites.net/).
2. Enter any number and save it in the **Memory** space.
3. Delete the **Memory** space. 
4. Enter any other number and try to save it in the **Memory** space.

### **Actual behavior:**

- It always save the the number that is saved very first time.
- It remembers the first value and doesn't clear the cache.
- By refreshing the page it will clear the cache and user can save new number in **Memory**.

### **Expected behavior:**

- Deleting the **Memory** also clear the cache and user can save any number after clearing the **Memory** space.

### **Attachment:**

[Clear_cache_video.zip](https://github.com/nventive/calculator/files/3267555/Clear_cache_video.zip)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+472
 - **Environment:** Firefox, Chrome and Microsoft Edge 

### **Notes:**
- Refer the attached video to get better idea.
- Crosschecked with windows calculator.

**Comment by jeromelaban** [comment]
~~The rounding used by C#/.NET after translation differs from the one used in C++, this is an expected result.~~

**Comment by davidjohnoliver** [comment]
> The rounding used by C#/.NET after translation differs from the one used in C++, this is an expected result.

@jeromelaban Wrong issue?

**Comment by jeromelaban** [comment]
Yep sorry about that.

**Comment by carldebilly** [comment]
This is a bug in Uno we can't fix easily.
https://github.com/nventive/Uno/issues/1046

Will be fixed by replacing the `List<string>` by an observable collection.

**Comment by Hpancha** [comment]
This issue is still occurring. Cache memory does not clear after deleting the memory using **MC** key.
**Version:** 0.1.0-uno.1+486

**Comment by jeromelaban** [comment]
There are unknown mono-wasm AOT issues around the memory list, causing this issue in staging.
