### ISSUE TITLE
[All] Resing the window flush the inputs and result

### ISSUE THREAD

**Issue by dr1rrb** [nventive/calculator#125]
**Describe the bug**
When resizing the window, all values (inputs and result) are cleared, even the selected Unit for converters.

**Steps To Reproduce**
1. Goto any converter
1. Hit `1`
1. Resize the window

**Expected behavior**
Not cleared

**Comment by Hpancha** [comment]
This issue is no longer occurred on latest WASM build.
**Version:** 0.1.0-uno.1+486
