### ISSUE TITLE
Memory view button in narrow view shows transparent list after clear

### ISSUE THREAD

**Issue by jeromelaban** [nventive/calculator#129]
**Describe the bug**
An empty narrow view memory list is transparent

**Steps To Reproduce**
- Use the narrow view (e.g. phone)
- tap `M+`
- Tap in the empty area at the left of the `MS` button
- Clear the list

**Expected behavior**
The empty list is shown properly

**Screenshots**

**Device and Application Information**
 - Application Version: 0.1.0-uno.1+194

**Comment by davidjohnoliver** [comment]
@dr1rrb This looks similar to the problem that you fixed for the history list?

**Comment by jeromelaban** [comment]
definitely does.

**Comment by Hpancha** [comment]
This issue is no longer occurred on the latest build.
**Version:** 0.1.0-uno.1+499
