### ISSUE TITLE
Memory View button is empty

### ISSUE THREAD

**Issue by jeromelaban** [nventive/calculator#130]
**Describe the bug**
The narrow view memory list button is empty

**Steps To Reproduce**
- Use the narrow view (e.g. phone)
- tap `M+`
- A `M` with a down arrow should be in the empty area at the left of the `MS` button

**Expected behavior**
The button appears properly

**Device and Application Information**
 - Application Version: 0.1.0-uno.1+194

**Comment by Hpancha** [comment]
This issue is no longer occurred on the latest build.
**Version:** 0.1.0-uno.1+499
