### ISSUE TITLE
android: hidden elements are visible

### ISSUE THREAD

**Issue by ghuntley** [nventive/calculator#164]
**Describe the bug**

![Screenshot_20190629-224340](https://user-images.githubusercontent.com/127353/60477029-241cd000-9cc1-11e9-8547-36a1cedde741.jpg)

**Steps To Reproduce**

TBA

**Device and Application Information**
 - OS Build: TBA
 - Architecture: TBA
 - Application Version:
 - Region: 
 - Dev Version Installed: 
 

**Additional context**
Reported via info@, awaiting additional information.

**Comment by ghuntley** [comment]
Potentially related to this as well:

![Screenshot_20190627-232732_Uno Calc](https://user-images.githubusercontent.com/127353/60477624-1ff1b200-9cc3-11e9-94e6-5d70570322f4.jpg)

**Comment by ghuntley** [comment]
![Screenshot_20190627-200555](https://user-images.githubusercontent.com/127353/60477717-6f37e280-9cc3-11e9-848e-39ae82bb0d66.png)

**Comment by ghuntley** [comment]
Devices:
- OnePlus 6 with Android Version 9.
- Android 9 on Nokia 5 (2017)
- Samsung Galaxy S10 on Android 9.0
- Samsung Galaxy C7 on Android 8.0
- Samsung Galaxy Tab A2 on Android 8.1 (SM-T385C)

**Comment by carldebilly** [comment]
Probably related to #163
