### ISSUE TITLE
Color doesn't change to pink for some areas of the application 

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#173]
### **Steps To Reproduce:**

1. Visit [WASM Calculator](http://calculator-wasm-staging.azurewebsites.net/?theme=Pink).
2. Observe the selection line for **Memory** or **History**.

### **Actual behavior:**

- There are following areas where the color is still blue.
       - Selection underline for any selected menu option.
       - Numbers saved in the **Memory** and **History**.
       - Numbers entered in any of the converters.
       - Binary numbers in the **Programmer** calculator.
       - **About** pop-up.

### **Expected behavior:**

- As per the pink the pink theme, The above mentioned areas should also have the pink color.
 
### **Attachment:**

![SelectionLine_Menu](https://user-images.githubusercontent.com/51453677/60978194-c6126d00-a2fe-11e9-892b-4bcbf2ed11ae.png)

![HistoryText](https://user-images.githubusercontent.com/51453677/60978203-c9a5f400-a2fe-11e9-99ef-2305571de20b.png)

![Converters](https://user-images.githubusercontent.com/51453677/60978210-cca0e480-a2fe-11e9-81f2-f3626eacf6c4.png)

![Binary_Numbers](https://user-images.githubusercontent.com/51453677/60980485-8e0d2900-a302-11e9-97b0-b657d60c9ac6.png)

![About](https://user-images.githubusercontent.com/51453677/60978226-d0346b80-a2fe-11e9-8447-5fde4473f22d.png)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+541
 - **Environment:** Chrome

### **Note:**
- Refer the attached images to understand the issue.

**Comment by carldebilly** [comment]
Thanks for reporting : won't be fixed.
