### ISSUE TITLE
[High Contrast/Pink] Pressed state has the different color for certain keys

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#174]
### **Steps To Reproduce:**

1. Visit [WASM Calculator Pink Theme](http://calculator-wasm-staging.azurewebsites.net/?theme=Pink).
2. Go to the **Standard** calculator.
3. Press and hold the Divide key (÷) and observe the pressed state.

### **Actual behavior:**
- It occurs for all three types of calculators.
- The color of the pressed state is blue for following five keys.
      - Divide (÷)
      - Multiply (×)
      - Plus (+)
      - Minus (-)
      - Equal to (=)
### **Expected behavior:**

- All keys have the same color for the pressed state.

### **Attachment:**

![Pressed_State](https://user-images.githubusercontent.com/51453677/60979736-391ce300-a301-11e9-970f-c71ca2eac6b9.png)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+541
 - **Environment:** Chrome

### **Note:**
- Refer the attached image to understand the issue.
- The same issue also occurs with the **High Contrast** theme calculator as well.

**Comment by carldebilly** [comment]
PR #175 will probably fix those.

**Comment by carldebilly** [comment]
Fixed
