### ISSUE TITLE
Number keys don't work

### ISSUE THREAD

**Issue by epexa** [nventive/calculator#323]
Number keys (0-9) don't work.
From [Snap](https://snapcraft.io/uno-calculator).

- OS Build: Ubuntu 20.04 
- Architecture: x86_64
- Application Version: 1.2.4-uno.707

**Comment by jeromelaban** [comment]
Thanks for the report @epexa!


This is a work in progress in Uno Platform: https://github.com/unoplatform/uno/issues/4318. We`ll update the calculator as the work progresses.

**Comment by epexa** [comment]
Fixed, thanks!

Application Version: 1.2.4-uno.725
